import React from 'react'
import { 
    HomeOutlined, 
    WechatOutlined, 
    CalendarOutlined, 
    FileSyncOutlined, 
    MailOutlined, 
    BookOutlined, 
    FormOutlined, 
    QuestionCircleOutlined, 
    ShoppingOutlined,
    AppstoreOutlined,
    SnippetsOutlined,
    SettingOutlined,
    NotificationOutlined
} from '@ant-design/icons';

const NavItems = [
    {
        name: `Home`,
        link: '/home',
        icon: <HomeOutlined />,
        badge: 1,
        hide : true,
        subMenu: [],
    },
    {
        name: `Chat`,
        link: '/chat',
        icon: <WechatOutlined />,
        badge: 1,
        hide : true,
        subMenu: [],
    },
    {
        name: `Calendar`,
        link: '/calendar',
        loadDirect: `/calendar`,
        icon: <CalendarOutlined />,
        badge: 1,
        hide : true,
        subMenu: [],
    },
    {
        name: `Files`,
        link: '/files',
        loadDirect: `/files`,
        icon: <FileSyncOutlined />,
        badge: 1,
        hide : true,
        subMenu: [],
    },
    {
        name: `Mailbox`,
        ancor: `https://mail.google.com/mail/u/0/?tab=km#inbox  `,
        icon: <MailOutlined />,
        badge: 1,
        hide : true,
        subMenu: [],
    },
    {
        name: `Knowledge`,
        link: '/knowledge',
        icon: <BookOutlined />,
        badge: 1,
        hide : true,
        subMenu: [],
    },
    {
        name: `Blogs`,
        link: '/blogs',
        icon: <FormOutlined />,
        badge: 1,
        hide : true,
        subMenu: [],
    },
    {
        name: `Grades`,
        link: '/grades',
        icon: <SnippetsOutlined />,
        badge: 1,
        hide : true,
        subMenu: [],
    },
    {
        name: `College Applications`,
        link: '/college_applications',
        icon: <AppstoreOutlined />,
        badge: 1,
        hide : true,
        subMenu: [],
    },
    {
        name: `MEP Store`,
        link: '/store',
        icon: <ShoppingOutlined />,
        badge: 1,
        hide : true,
        subMenu: [],
    },
    {
        name: `FAQ`,
        link: '/faq',
        icon: <QuestionCircleOutlined />,
        badge: 1,
        hide : true,
        subMenu: [],
    },
    // {
    //     name: `Profile`,
    //     link: '/profile',
    //     // icon: <CreditCardFilled />,
    //     badge: 1,
    //     subMenu: [],
    // },
    
    {
        name: `Academic Support`,
        link: '/academic_support',
        icon: <SettingOutlined />,
        hide : false,
        badge: 1,
        subMenu: [],
    },
    {
        name: `Notifications`,
        link: '/notifications',
        icon: <NotificationOutlined />,
        hide : false,
        badge: 1,
        subMenu: [],
    }
]

export default NavItems;